library(devtools) 
library(sentimentr)
library(dplyr) 
library(RColorBrewer) 
library(wordcloud)
sentiment("I am excited") 
sentiment("I am not excited") 
mytext <- c('I am happy and excited.  This is my first R application with sentiment scoring') 
sentiment(mytext) 
