library(devtools) 
library(sentimentr)
library(dplyr) 
library(RColorBrewer) 
library(wordcloud)
sentiment("I am excited") 
sentiment("I am not excited") 
mytext <- c('I am happy and excited.  This is my first R application with sentiment scoring') 
sentiment(mytext) 
x<-c("There are two most widely used methods for sentiment analysis: classiﬁer based methods and lexicon based methods. In a classiﬁer based approach, a dataset comprising text with labels (can be polarity, sentiment strength or emotions) is input to a machine learning algorithm, which in turn builds a model for classiﬁcation. The learnt model is then used to predict the sentiments present in a given text sample. The second approach is the lexicon based approach, in which a dictionary of English words is maintained, each word having a corresponding sentiment label associated with it. This dictionary is also referred to as a sentiment lexicon. A given text sample is then classiﬁed based on an overall score of sentiments of the words comprising the sentence, where the individual scores are obtained via dictionary lookups.")
sentiment(x) 
